# Generated by Django 4.2.7 on 2025-10-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_editor', '0002_alter_graphproject_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_type', models.CharField(choices=[('node', 'Node Type'), ('connection', 'Connection Type')], max_length=20)),
                ('type_identifier', models.CharField(max_length=100)),
                ('definition_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_definitions', to='node_editor.graphproject')),
            ],
            options={
                'ordering': ['definition_type', 'type_identifier'],
                'unique_together': {('project', 'definition_type', 'type_identifier')},
            },
        ),
        migrations.AddIndex(
            model_name='projecttypedefinition',
            index=models.Index(fields=['project', 'definition_type'], name='node_editor_project_def_idx'),
        ),
    ]