# Generated by Django 4.2.7 on 2025-10-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_editor', '0003_projecttypedefinition'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projecttypedefinition',
            new_name='node_editor_project_204c3d_idx',
            old_name='node_editor_project_def_idx',
        ),
    ]
