# Generated by Django 4.2.16 on 2025-10-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_editor', '0004_rename_node_editor_project_def_idx_node_editor_project_204c3d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttypedefinition',
            name='python_class_path',
            field=models.CharField(blank=True, help_text='Python import path to the plugin class', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NodeTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_type', models.CharField(choices=[('node', 'Node Type'), ('connection', 'Connection Type')], max_length=20)),
                ('type_identifier', models.CharField(max_length=100)),
                ('definition_data', models.TextField()),
                ('python_class_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['definition_type', 'type_identifier'],
                'unique_together': {('definition_type', 'type_identifier')},
            },
        ),
        migrations.AddIndex(
            model_name='nodetypedefinition',
            index=models.Index(fields=['definition_type'], name='node_editor_definit_9f0e1d_idx'),
        ),
    ]