# Generated by Django 4.2.7 on 2025-10-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_editor', '0005_add_python_class_path_and_global_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nodetypedefinition',
            new_name='node_editor_definit_82afda_idx',
            old_name='node_editor_definit_9f0e1d_idx',
        ),
    ]
